name: hosts-ip-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"


permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Hosts IP
      run: |
        pwd
        bash $GITHUB_WORKSPACE/google/hosts-ip-update.sh
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-Build"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
