name: Unify Hosts File

on:
  workflow_dispatch:
  workflow_run:
        workflows: ['Generate Hosts File']
        types: [completed]
#  schedule:
#    - cron: "0 * * * *"


permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python-abp
      run: |
        python -m pip install --upgrade pip
        pip install python-abp
    - name: Unify Hosts File
      run: |
        flrender $GITHUB_WORKSPACE/hosts.template $GITHUB_WORKSPACE/hosts.txt
        flrender $GITHUB_WORKSPACE/hosts-ipv4only.template $GITHUB_WORKSPACE/hosts-ipv4only.txt
      
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "IP Update"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
